#ifndef LOG_H_INCLUDED
#define LOG_H_INCLUDED

#define MAIN_LOG 0
#define DIELECTRIC_LOG 0
#define CAMERA_LOG 0
#define HITABLE_LOG 0
#define HITABLE_LIST_LOG 0
#define ELLIPTIC_PLANE_LOG 0
#define TRIANGLE_LOG 0
#define POLYGON_LOG 0
#define BOX_LOG 0
#define SPHERE_LOG 0
#define TORI_LOG 0
#define TORI_PART_LOG 0
#define TORI_PART_ALL_LOG 0
#define QUADRATIC_ELLIPSOID_LOG 0
#define QUADRATIC_LOG 0
#define QUADRATIC_CYLINDER_ALL_LOG 0
#define QUADRATIC_PARABOLOID_LOG 0
#define QUADRATIC_HYPERBOLIC_PARABOLOID_LOG 0
#define MATERIAL_LOG 0
#define LAMBERTIAN_LOG 0
#define METAL_LOG 0
#define RAY_LOG 0
#define VEC3_LOG 0
#define QUARTIC_BLEND_CYLINDER_LOG 0
#define SUPERELLIPSOID_LOG 0
#define SUPERQUADRATIC_LOG 0
#define SUPERHYPERBOLOID_LOG 0
#define SUPERTOROID_LOG 0
#define RAIN_LOG 0
#define PARAMETRIC_SURFACE_LOG 0
#define SWEEPING_TRANSLATIONAL_LOG 0
#define SWEEPING_ROTATIONAL_LOG 0
#define SWEEPING_SPHERE_LOG 0

#endif // LOG_H_INCLUDED
